### ISSUE TITLE
Setup accounts for the deployment services. 

### ISSUE THREAD

**Issue by bauff** [synchronizing/Sports-Portfolio#12]
Someone please create a shareable [Gmail](http://gmail.com) account for this project, and register to the following with it:

* [MLab](https://mlab.com/signup/)
* [Heroku](https://www.heroku.com/)

Please share its info as a reply to this, and share it on Slack. Once the Heroku account is set-up, make sure to test our boilerplate:

1. Pull the repo, and try hosting on Heroku on their free plan.
2. Sync the Heroku repo with the master branch on GitHub so it's always updated.
3. Document the URL and credentials Heroku provides and share in Slack and below.

**Comment by synchronizing** [comment]
@zsaadioui Created the Gmail account. 

* **Email:** teamsportics@gmail.com
* **Password:** Posted on Slack [here](https://team1cen.slack.com/archives/CGBT98DFV/p1553641274001000).

**Comment by timdoozy** [comment]
I setup the mlab and heroku account and put the information in slack #technical. @synchronizing you are probably going to be the one to setup the heroku since I think you control the repo on github.

**Comment by synchronizing** [comment]
@timdoozy Oh, good point dude. Will put it on my to-do list -- we only need it for official deployment.

**Comment by timdoozy** [comment]
There is a pinned post in slack #technical with mlab, heroku, and gmail information. I think this issue is good to be closed.
