### ISSUE TITLE
Create BackEndService to handle requests to the server

### ISSUE THREAD

**Issue by bauff** [synchronizing/Sports-Portfolio#27]
From what I understand components are meant to hold views and logic specific to the component and data is meant to be fetched using services.
read more: https://angular.io/guide/architecture-services

So we should make a service that handles making appropriate requests to the backend so we can inject this data directly into our components.

**Comment by bauff** [comment]
Could also be useful: https://v6.angular.io/guide/http

**Comment by timdoozy** [comment]
I found a good guide on how to connect our backend to the frontend via services and components as well.  https://www.sitepoint.com/mean-stack-angular-2-angular-cli/

I had some time over the weekend to get started on the services. I will push a new branch "cardservice" with the initial card service, card interface, and view card component. Check it out and let me know what you guys think 👌

**Comment by synchronizing** [comment]
@timdoozy Did you remove the PR?

**Comment by timdoozy** [comment]
Pull request #47 implemented the card service. Tomorrow Noah and I will begin working on implementing the order service.

**Comment by synchronizing** [comment]
@timdoozy + @bauff have been able to complete this and it has been pushed to master.
