### ISSUE TITLE
Add schemas to the project.

### ISSUE THREAD

**Issue by synchronizing** [synchronizing/Sports-Portfolio#5]
As of now, I believe the way we have the schemas set-up on our slides is probably fine, however I do not believe we would need the `Cart` schema. We could utilize `Order` with the `confirmed` column as a mean to keep track of whether or not it has been purchased, and therefore a substitute for `Cart`. Thoughts?

customerID | fullName | email | hashedPassword | createdAt | roles
-- | -- | -- | -- | -- | --
0 | Rick Strattum | rick@me.com | md5_pass | 2019-03-11 | [admin, user]

cardID | bought | playerName | team | Description | sport | images | createdAt
-- | -- | -- | -- | -- | -- | -- | --
0 | False | Allen Iverson | Philadelphia 76ers | Collector’s Edge Rookie Rage - Die Cuts | Basketball | [http://, http://] | 2019-03-11
1 | False | David Ortiz | Boston Red Sox | #110 of 300, 2004, Bazooka | Baseball | [http://, http://] | 2019-03-11

orderID | customerID | cardIDs | price | confirmed | createdAt
-- | -- | -- | -- | -- | --
0 | 0 | [0, 1] | $543 | False | 2019-03-11

**Comment by synchronizing** [comment]
note: @timdoozy added pull-request #8 , pending review

**Comment by timdoozy** [comment]
You should cancel pull request #8. I have changed a lot since 11 days ago.
