### ISSUE TITLE
Establish the Express.js API routes for the application.

### ISSUE THREAD

**Issue by bauff** [synchronizing/Sports-Portfolio#6]
We need documentation for an API so back-end can begin writing routes and front-end will know what routes to hit.

**At a high level our API should handle**
- Retrieving a card from DB and store in client's memory
- Adding a card form client's memory to a user's cart in DB
- Retrieving a user's cart from DB
- Removing a card from a user's cart and updating DB
- Sending user's cart to our _email service_

This should easily follow CRUD, if there's anything you think is missing post a comment.

**NOTE**: Something that might be of interest is using `swagger` which is already built into our project because of the mean.io boilerplate. 
---> SEE `./server/config/swagger.json` and edit that.

**Recommended resources**
[API Design suggestions](https://swagger.io/resources/articles/best-practices-in-api-design/
) 
[Sample Swagger.json and preview editor]( https://editor.swagger.io/?_ga=2.256485826.830443135.1552659582-262302583.1552333353)

**Comment by synchronizing** [comment]
@bauff @timdoozy @imnoahcook @zsaadioui Who will be taking care of the routes for the project?

**Comment by synchronizing** [comment]
@imnoahcook Has said he will take responsibility for this.

**Comment by timdoozy** [comment]
Pull request #24 has the card and order routes implemented. From here, where should we go now?

**Comment by synchronizing** [comment]
This has been completed by @imnoahcook and @timdoozy. Closing issue.
